### ISSUE TITLE
Doesn’t work on facebook site 

### ISSUE THREAD

**Issue by maxime1455** [ulyngs/mindshield-open-source#1]
Hello brother, the extension doesn’t work on facebook.

**Comment by maxime1455** [comment]
can you fix that ?

**Comment by ulyngs** [comment]
Can you let me know what language you are using Facebook in and what device (iPhone, iPad, mac?)? Is the extension working on all the other sites for you?

**Comment by maxime1455** [comment]
french and iphone

Le mar. 20 déc. 2022 à 12:54, Ulrik Lyngs ***@***.***> a
écrit :

**Comment by maxime1455** [comment]
yes it does work on ytb and insta

**Comment by maxime1455** [comment]
it blocks nothing on fb

**Comment by ulyngs** [comment]
Strange -- I just tried changing the language to French on my iPhone and it still works for me:

![IMG_2384](https://user-images.githubusercontent.com/23137032/209104600-c7f277f9-4db4-4cfc-8bcc-200282f95438.PNG)


Can you 

- let me know what specific iPhone you have (e.g. iPhone 14 etc.) 
- post a screenshot of your Facebook page with the MindShield settings open
