### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by dannflor** [ulyngs/mindshield-open-source#10]
After the latest update, settings are no longer persisting between sessions. You have to re-check the boxes every time

**Comment by ulyngs** [comment]
Just noticed this too, apologies!! I introduced this bug by mistake in the last update... 😱

I've just fixed it and submitted an update to the App Store -- it should be out in the next day or two!

**Comment by ulyngs** [comment]
Update is out! Can you confirm that the fix works?
