### ISSUE TITLE
Instagram: the feed is no longer hidden

### ISSUE THREAD

**Issue by robertc-ball** [ulyngs/mindshield-open-source#13]

**Comment by ulyngs** [comment]
Can you provide a bit more detail? I just tested on my own devices, and the feed hiding works both on laptop and iPhone for me? 

<img width="837" alt="image" src="https://github.com/ulyngs/mindshield-open-source/assets/23137032/acf9f2bf-9c18-4748-a098-fcb9abf0685d">
![IMG_0008](https://github.com/ulyngs/mindshield-open-source/assets/23137032/9d449acd-aba7-4507-8dcf-305ed937c7a6)

**Comment by ulyngs** [comment]
Perhaps fixed in the latest version i just submitted
