### ISSUE TITLE
YouTube:hiding shorts after searching for video

### ISSUE THREAD

**Issue by Marian230** [ulyngs/mindshield-open-source#14]
There already is option to hide shorts. But it only hides shorts section. 

When i search for some video. For example “cooking steak”, first recomended video is short. 

So option to hide shorts from searching result would be great.

**Comment by ulyngs** [comment]
Agreed -- I was thinking that maybe when you hide 'shorts', it should just hide shorts everywhere, including in the search results? Or do you think some people might want to hide only the shorts menu button, but still see them in results?

**Comment by ulyngs** [comment]
I believe this has been resolved
