### ISSUE TITLE
Hiding youtube notifications not permanent

### ISSUE THREAD

**Issue by CLEMSOUYT** [ulyngs/mindshield-open-source#20]
Hi i am on ipad os and i would like to hide YouTube notifications.

whenever i do it, the notifications button disappears but reappears in every other tabs .

it is just applying once.

Could you please fix it please ?

Thank you very much !

![IMG_0016](https://github.com/ulyngs/mindshield-open-source/assets/89974535/f9766585-3472-43a5-ae93-368899c409fc)
![IMG_0017](https://github.com/ulyngs/mindshield-open-source/assets/89974535/044a8165-265f-4991-94d9-51805713b6f4)
![IMG_0024](https://github.com/ulyngs/mindshield-open-source/assets/89974535/73f093ac-b983-40b3-8dac-4c158eb9fb8b)

**Comment by alhay491** [comment]
This is the same for video thumbnail as well
