### ISSUE TITLE
Remove the Instagram Explore Page

### ISSUE THREAD

**Issue by vasco-seo** [ulyngs/mindshield-open-source#24]
Hey, can you please add an option where the IG explore page feed is removed?

I find myself getting lost in time mindlessly scrolling when I click the little "magnifying glass". If it's easier, you don't need to remove the "magnifying glass", just the content that shows up after you click it. (check image)

![1](https://github.com/ulyngs/mindshield-open-source/assets/159809111/9f8154e5-9ff5-44f6-b681-103c4f1efb29)

Thanks!

**Comment by ulyngs** [comment]
added in upcoming v1.18
