### ISSUE TITLE
YouTube: Account image blocking is not working

### ISSUE THREAD

**Issue by dannflor** [ulyngs/mindshield-open-source#27]
Even with “Account Images” selected, they are still not blocked

**Comment by ulyngs** [comment]
Interesting --- can you let me know if this is on Mac or iPhone?

And is it on the home screen? (it's working for me:

<img width="1010" alt="image" src="https://github.com/ulyngs/mindshield-open-source/assets/23137032/5e0ff79d-eaeb-4c33-b223-71ca13dc3b66">


<img width="1022" alt="image" src="https://github.com/ulyngs/mindshield-open-source/assets/23137032/4709b0cb-3ffe-414a-91ad-296be0fa1239">

**Comment by ulyngs** [comment]
ah great, thanks for clarifying, will have a look now

**Comment by ulyngs** [comment]
fixed in upcoming v1.18
