### ISSUE TITLE
The app stopped working on my IG feed

### ISSUE THREAD

**Issue by tuamae12345** [ulyngs/mindshield-open-source#28]
Hello, the app stopped working on my IG. What can I do?

**Comment by ulyngs** [comment]
Thanks for flagging this – someone else just notified me via email too, will try to find time to fix this week!

Best,
Ulrik

**Comment by ulyngs** [comment]
Can you

-  let me know which device this is? I am assuming iPhone?
- let me know whether the extension opens as normal, it's just nothing anything, or whether you can't even open the extension?

**Comment by ulyngs** [comment]
Caught it -- Instagram has changed the mobile HTML. Should be fixed in upcoming v1.18 this week
