### ISSUE TITLE
Add extra option to blocking thumbnails.

### ISSUE THREAD

**Issue by BroMan283** [ulyngs/mindshield-open-source#30]
Instead of completely removing thumbnails or blurring them can you please also add an option to just have a solid colour to replace the thumbnails with? Removing them completely just messes up the order of stuff and looks unclean and the blurring just looks out of place to me. It’ll be really helpful if we could chose to replace it with a solid colour like grey or something. Thanks :)

**Comment by BroMan283** [comment]
![IMG_0169](https://github.com/ulyngs/mindshield-open-source/assets/168827820/289f4f66-8da8-4774-9bfc-4f8be813b4d4)
Something like this

**Comment by ulyngs** [comment]
Just added with [d9fafed](https://github.com/ulyngs/mindshield-open-source/commit/d9fafeda30378863097c89cf3884d683279e443e) --- you can now make them completely black in addition to blurring them. Will be included in update next week
