### ISSUE TITLE
x.com needs to be added to Sites

### ISSUE THREAD

**Issue by johnpilbeam** [ulyngs/mindshield-open-source#31]
It looks like X finally made the switch from twitter.com to x.com. At least for me, twitter.com now redirects to x.com where Mindshield does apply the settings that I had set up for twitter.com. If Twitter is now gone, perhaps the easiest thing is for just replace twitter.com with x.com in Sites and have any existing Twitter user settings apply to X.

**Comment by ulyngs** [comment]
Thank you for flagging this, I'll fix in the next update! I am swamped the next weeks with a major deadline but will try to get an update out as soon as possible. Thanks for being patient!! 🙏
