### ISSUE TITLE
YouTube notification/blurred thumbnails do not get saved correct

### ISSUE THREAD

**Issue by SuneGraversen** [ulyngs/mindshield-open-source#32]
The code below for saving the settings only save the .checked-field of each button in the popup. However, notifications and thumbnail settings for youtube use a data-state attribute. Thus those do not get saved.

https://github.com/ulyngs/mindshield-open-source/blob/3db007e8a4c3cd84fc17e95b713f1082312db4c8/Shared%20(Extension)/Resources/popup.js#L403-L406

I will open a pull-request to solve this.

**Comment by ulyngs** [comment]
whoops, you're completely correct, thanks for catching and correcting this!!
