### ISSUE TITLE
Clean up Extension Icon so it does not have blue/gray box around it

### ISSUE THREAD

**Issue by CrazyLegion** [ulyngs/mindshield-open-source#34]
<img width="44" alt="Screenshot 2024-06-08 at 12 49 21 PM" src="https://github.com/ulyngs/mindshield-open-source/assets/109924869/bf10bea6-7e2f-47fc-8f39-a18b8088726c">
<img width="88" alt="Screenshot 2024-06-08 at 12 50 57 PM" src="https://github.com/ulyngs/mindshield-open-source/assets/109924869/2078cb44-1e52-4b0c-b88f-dec5a2832b98">
<img width="89" alt="Screenshot 2024-06-08 at 12 55 43 PM" src="https://github.com/ulyngs/mindshield-open-source/assets/109924869/683686b9-45bf-45a9-83bf-dfefcf7906d4">

**Comment by ulyngs** [comment]
Fixed in [d04ed51](https://github.com/ulyngs/mindshield-open-source/commit/d04ed51be09bfe56d96998993da52f5648a2fe9f) following @dannflor's suggested solutions - will be included in next update next week
