### ISSUE TITLE
Newsfeed and Stories not blocked on Facebook  with mobile extension

### ISSUE THREAD

**Issue by dannflor** [ulyngs/mindshield-open-source#9]
![image](https://user-images.githubusercontent.com/59743986/229239757-acbe40e7-b248-4a3f-a1ef-f13311c42580.png)

**Comment by ulyngs** [comment]
Thanks for flagging, will look into this now!!

**Comment by ulyngs** [comment]
Found the newsfeed bug -- the Stories still seems to work?

I've submitted an update to the app store, it should be out in a day or two, let me know if there's still an issue after you've updated!!
